name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  test-macos:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Test
        run: |
          xcodebuild test \
            -scheme Gibbous \
            -destination 'platform=macOS' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO
